### ISSUE TITLE
Looking for help

### ISSUE THREAD

**Issue by leesf** [justinrmiller/brauhaus#1]
Hi, your KeyedStore implements Storehaus of twitter, and do you know how to integrate your KeyedStore  with summingbird? Thanks a lot for your answering.

**Comment by justinrmiller** [comment]
Hi leesf, sorry for taking a while to get back to this, was doing a bit of vacationing. If your project w/Summingbird uses Storehaus stores, it's pretty straightforward to use and I can provide example. I'm not particularly familiar with Summingbird but it does look like that Scalding store in Summingbird is a different interface (Store). The idea though is pretty straightforward and could likely be re-implemented for your particular application. Do you have an example in mind?

Storehaus Store:
https://github.com/twitter/storehaus/blob/master/storehaus-core/src/main/scala/com/twitter/storehaus/Store.scala

**Comment by leesf** [comment]
Hey, sorry to trouble you again, i would appreciate it if you could provide an example to me, and then i can alter the example you provided to satisfy me own needs. Thank you a lot.
